Groovy to KTS migration
google-developer-training/basic-android-kotlin-compose-training-tip-calculator pull request #121
Opened 2023-06-08 21:54 UTC by android-dev-lxl

2023-06-09 14:28 UTC, johnshea requested changes
`settings.gradle.kts` is missing its license.
`AndroidManifest.xml` remove blank line in `<intent-filter>` (line 35)
`themes.xml` remove blank line on line 18

2023-06-09 14:28 UTC, johnshea commented on app/build.gradle.kts
> +                getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
nit: move 2nd argument to a new line.

2023-06-09 14:28 UTC, johnshea commented on app/build.gradle.kts
> +        freeCompilerArgs += "-opt-in=androidx.compose.material3.ExperimentalMaterial3Api"
Is this still needed?

2023-06-09 14:28 UTC, johnshea commented on build.gradle.kts
> +    id("com.android.application") version "8.0.1" apply false
Update all versions

2023-06-09 23:05 UTC, android-dev-lxl commented on app/build.gradle.kts
> +                getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
I can move it, when I reformat the file AS removes this line.
There is no point in keep adding the line

2023-06-12 19:18 UTC, johnshea approved these changes

2023-07-21 23:16 UTC, merged