Test solution E2E
google-developer-training/basic-android-kotlin-compose-training-tip-calculator pull request #129
Opened 2023-08-01 23:53 UTC by android-dev-lxl

In this PR:

- Added Edge to Edge.
- Removed unused variable, `focusManager`. 
- Corrected the vertical alignment for **Round the tip amount** `Row`.

2023-08-09 11:43 UTC, johnshea requested changes
- Navigation bar is not translucent. It is not showing the bottom of the letter "p" that descends.
- App is not going to the left edge when in landscape orientation.
<img width="678" alt="Screenshot 2023-08-09 at 2 08 52 PM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/assets/7107817/16a8b796-8487-4bc8-b0c5-92005a346307">

2023-08-09 11:43 UTC, johnshea commented on app/src/main/java/com/example/tiptime/MainActivity.kt
nit: Remove `id =` on line 146. Function takes one argument so not needed.

2023-08-15 20:15 UTC, android-dev-lxl commented on app/src/main/java/com/example/tiptime/MainActivity.kt
Leaving it as is for consistency

2023-08-15 20:16 UTC, android-dev-lxl commented
> * Navigation bar is not translucent. It is not showing the bottom of the letter "p" that descends.
> * App is not going to the left edge when in landscape orientation.
> 
> <img alt="Screenshot 2023-08-09 at 2 08 52 PM" width="678" src="https://user-images.githubusercontent.com/7107817/259394416-16a8b796-8487-4bc8-b0c5-92005a346307.png">

This will be as is: 
>App is not going to the left edge when in landscape orientation.

2023-08-16 22:28 UTC, johnshea submitted a review, later dismissed
LGTM with one small change.

- Update androidTestImplementation BOM to the latest version (Currently `2023.08.00`)

2023-08-21 14:29 UTC, johnshea requested changes
API 33 e2e UI changed and no longer matches pre e2e API 33 UI.

Note - PR was approved (e2e UI was correct) but subsequent commits after approval changed the UI so it was un-approved.

<img width="759" alt="Screenshot 2023-08-21 at 10 29 16 AM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/assets/7107817/28f13c70-8cef-4186-979a-b8bae324becd">

2023-08-21 17:25 UTC, android-dev-lxl commented
<img width="256" alt="image" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/assets/24260141/b928db85-f4af-4214-a3c0-69f4da61191b">


> API 33 e2e UI changed and no longer matches pre e2e API 33 UI.
> 
> Note - PR was approved (e2e UI was correct) but subsequent commits after approval changed the UI so it was un-approved.
> 
> <img alt="Screenshot 2023-08-21 at 10 29 16 AM" width="759" src="https://user-images.githubusercontent.com/7107817/262054186-28f13c70-8cef-4186-979a-b8bae324becd.png">

I am not able to reproduce:

<img width="256" alt="image" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/assets/24260141/8f61e12b-1691-4ae8-8a0f-51101dd5653f">

2023-08-25 15:58 UTC, johnshea requested changes
Navigation bar is not translucent (Pixel 6 API 33) but should be.

<img width="554" alt="Screenshot 2023-08-25 at 11 40 13 AM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/assets/7107817/82efb6b5-65a0-47b0-ab1b-2935d9deddf6">

API 24 - Navigation bar is not translucent but should be. (Note - I added additional Text to test.)

<img width="387" alt="Screenshot 2023-08-25 at 11 42 23 AM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/assets/7107817/9ea04a20-ce76-4e29-b63c-19d65b46804b">

API 26 - Navigation bar is not translucent but should be. (Note - I added additional Text to test.)

<img width="385" alt="Screenshot 2023-08-25 at 11 42 32 AM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/assets/7107817/cc983c94-65e2-49b1-91ed-675eb544dff5">

2023-08-25 15:58 UTC, johnshea commented on build.gradle.kts
> +        set("compose_compiler_version", "1.5.1")
Upgrade to latest.

2023-08-25 15:58 UTC, johnshea commented on build.gradle.kts
> +    id("com.android.application") version "8.1.0" apply false
Upgrade to latest.

2023-08-25 15:58 UTC, johnshea commented on build.gradle.kts
> +    id("com.android.library") version "8.1.0" apply false
Upgrade to latest.

2023-08-25 15:58 UTC, johnshea commented on app/src/main/java/com/example/tiptime/MainActivity.kt
> +                .padding(bottom = 16.dp, top = 40.dp)
Could we add 40.dp to the dimens.xml?

2023-08-25 15:58 UTC, johnshea commented on app/src/main/java/com/example/tiptime/MainActivity.kt
Could we add 32.dp to the dimens.xml?

2023-08-25 20:08 UTC, android-dev-lxl commented on app/src/main/java/com/example/tiptime/MainActivity.kt
> +                .padding(bottom = 16.dp, top = 40.dp)
Since this is the intial codelabs in the course we decided to not to use a dimens.xml file

2023-08-25 20:08 UTC, android-dev-lxl commented on app/src/main/java/com/example/tiptime/MainActivity.kt
No. Reply above.

2023-08-31 15:22 UTC, johnshea requested changes
UI has same issues https://github.com/google-developer-training/basic-android-kotlin-compose-training-tip-calculator/pull/135#pullrequestreview-1603615664

settings.gradle.kts - Can this be removed `@file:Suppress("UnstableApiUsage")` as you did in other PR?

2023-08-31 15:22 UTC, johnshea commented on app/src/main/java/com/example/tiptime/MainActivity.kt
> +import androidx.compose.foundation.layout.safeContentPadding
Remove unused imports.

2023-08-31 15:22 UTC, johnshea commented on build.gradle.kts
> +    id("org.jetbrains.kotlin.android") version "1.9.0" apply false
Update version.

2023-09-11 17:20 UTC, johnshea approved these changes
lgtm

2023-10-16 14:50 UTC, johnshea approved these changes
Approved but unused imports need to be removed.

2023-10-16 14:50 UTC, johnshea commented on app/src/main/java/com/example/tiptime/ui/theme/Theme.kt
>  import android.app.Activity
Remove unused imports.

2023-10-17 21:52 UTC, merged