App code M3
google-developer-training/basic-android-kotlin-compose-training-tip-calculator pull request #77
Opened 2023-03-16 01:56 UTC by android-dev-lxl

Added app code

<img src="https://user-images.githubusercontent.com/24260141/225489396-07b22a32-9789-4322-9e03-2185d96e3944.png" width=50% height=50%>

2023-03-16 18:47 UTC, kkuan2011 commented on app/src/main/java/com/example/tiptime/MainActivity.kt
> +@Composable
Will you also be able to include the changes from the design review? (e.g. top app bar, background color, etc..)

2023-03-17 23:40 UTC, android-dev-lxl commented on app/src/main/java/com/example/tiptime/MainActivity.kt
> +        modifier = Modifier.padding(32.dp),
We already use vertical arrangement, so I added horizontal arrangement. Would that be confusing? 

```
Column(
        modifier = modifier.padding(32.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) 
```

2023-03-23 13:11 UTC, johnshea commented on app/src/main/AndroidManifest.xml
>                  <action android:name="android.intent.action.MAIN" />
Remove the following blank line.

2023-03-23 13:15 UTC, johnshea commented on app/src/main/java/com/example/tiptime/MainActivity.kt
> + * according to the local currency and display it onscreen.
nit: This function does not "display it onscreen" as the comment states.

2023-03-23 13:21 UTC, johnshea commented on app/src/main/java/com/example/tiptime/ui/theme/Theme.kt
Remove blank line

2023-03-23 13:31 UTC, johnshea commented on app/src/main/res/drawable/percent.xml
> +<vector android:height="24dp" android:tint="#000000"
Does this need a license header?

2023-03-23 14:09 UTC, johnshea requested changes
Nit: Inconsistent usage of "http" / "https" in the copyright headers.

2023-03-23 14:13 UTC, johnshea commented on app/src/main/AndroidManifest.xml
>                  <action android:name="android.intent.action.MAIN" />
Remove the following blank line.

2023-03-23 17:18 UTC, android-dev-lxl commented on app/src/main/java/com/example/tiptime/MainActivity.kt
> +            modifier = modifier
We need to use the passed in Modifier. I fixed the issue .

2023-03-23 18:20 UTC, johnshea commented on app/src/main/java/com/example/tiptime/MainActivity.kt
> +            modifier = modifier
You did use it for the `Row` composable function.

2023-03-23 19:38 UTC, android-dev-lxl commented on app/src/main/java/com/example/tiptime/MainActivity.kt
> +            modifier = modifier
Removing it fixed it 
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/24260141/227331994-88a8a776-888a-422c-8777-f1dbc978d497.png">

2023-03-24 17:34 UTC, yenerm reviewed
lgtm

2023-03-24 21:23 UTC, MagicalMeghan commented on app/src/main/java/com/example/tiptime/MainActivity.kt
> +fun TipTimeLayout(modifier: Modifier = Modifier) {
don't need a modifier on the main Composable

2023-03-24 21:38 UTC, MagicalMeghan commented on app/src/main/java/com/example/tiptime/MainActivity.kt
> +            modifier = Modifier.padding(bottom = 32.dp)
32.dp is repeated over 3x - let's add it to the dimens file - same with any repeated dimen values

2023-03-24 21:38 UTC, MagicalMeghan commented on app/src/main/java/com/example/tiptime/MainActivity.kt
> +        shape = RoundedCornerShape(topStart = 16.dp, topEnd = 16.dp),
add 16.dp to dimens

2023-03-27 20:47 UTC, MagicalMeghan commented on app/src/main/java/com/example/tiptime/MainActivity.kt
> +        shape = RoundedCornerShape(topStart = mediumPadding, topEnd = mediumPadding),
You could add this to Shapes.kt file

2023-03-27 20:47 UTC, MagicalMeghan commented on app/src/main/java/com/example/tiptime/MainActivity.kt
> +            modifier = modifier
modifier = Modifier

2023-03-27 20:47 UTC, MagicalMeghan commented on app/src/main/java/com/example/tiptime/MainActivity.kt
> +        modifier = modifier.fillMaxWidth(),
pass this in through the parent

2023-03-27 20:47 UTC, MagicalMeghan commented on app/src/main/java/com/example/tiptime/MainActivity.kt
> +            fontWeight = FontWeight.Bold
font weight can be included in Type.kt as part of the displaySmall parameters

2023-04-08 00:31 UTC, android-dev-lxl commented on app/src/main/java/com/example/tiptime/MainActivity.kt
> +        shape = RoundedCornerShape(topStart = mediumPadding, topEnd = mediumPadding),
This is just one shape and this is a fairly complex codelab in the earlier units. 
Could we just leave it as is?

2023-04-10 21:05 UTC, MagicalMeghan commented on app/src/main/java/com/example/tiptime/MainActivity.kt
> +        shape = RoundedCornerShape(topStart = mediumPadding, topEnd = mediumPadding),
ok

2023-04-10 21:08 UTC, MagicalMeghan approved these changes

2023-04-10 21:26 UTC, merged